# 监听 master 分支
on:
  push:
    branches:
      - main

# action 名称
name: Contributes

jobs:
  # 任务
  contrib-readme-en-job:
    runs-on: macOS-latest
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_TOKEN }}
